import { Link, useLocation, useNavigate } from "react-router";
import { FaGoogle, FaTicketAlt, FaBus, FaMapMarkerAlt } from "react-icons/fa";
import { useForm } from "react-hook-form";
import { useContext, useState } from "react";
import toast from "react-hot-toast";
import axios from "axios";
import { AuthContext } from "../../Providers/AuthProvider";
import logo from "../../assets/logo.png";
import { Helmet } from "react-helmet-async";

const Login = () => {
  const { googleSignIn, signIn } = useContext(AuthContext);
  const navigate = useNavigate();
  const location = useLocation();
  const from = location.state?.from?.pathname || "/";
  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
  } = useForm();
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [activeTab, setActiveTab] = useState("login");

  // Demo credentials from environment variables
  const demoCredentials = {
    user: {
      email: import.meta.env.VITE_DEMO_USER_EMAIL,
      password: import.meta.env.VITE_DEMO_USER_PASSWORD,
    },
    vendor: {
      email: import.meta.env.VITE_DEMO_VENDOR_EMAIL,
      password: import.meta.env.VITE_DEMO_VENDOR_PASSWORD,
    },
    admin: {
      email: import.meta.env.VITE_DEMO_ADMIN_EMAIL,
      password: import.meta.env.VITE_DEMO_ADMIN_PASSWORD,
    },
  };

  // Check if demo credentials are available
  const isDemoAvailable =
    demoCredentials.user.email &&
    demoCredentials.vendor.email &&
    demoCredentials.admin.email;

  const handleDemoLogin = (role) => {
    const credentials = demoCredentials[role];
    setValue("email", credentials.email);
    setValue("password", credentials.password);
    toast.success(`Demo ${role} credentials loaded!`);
  };

  const onSubmit = async (data) => {
    setLoading(true);
    try {
      const result = await signIn(data.email, data.password);

      // Generate JWT token
      const tokenResponse = await axios.post(
        `${import.meta.env.VITE_API_URL}/jwt`,
        { email: result.user.email }
      );
      localStorage.setItem("token", tokenResponse.data.token);

      toast.success("Login successful!");
      navigate(from, { replace: true });
    } catch (error) {
      toast.error(error.message || "Login failed");
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleSignIn = async () => {
    setLoading(true);
    try {
      const result = await googleSignIn();

      // Save user to database if they don't exist
      await axios.post(`${import.meta.env.VITE_API_URL}/users`, {
        email: result.user.email,
        name: result.user.displayName,
        photoURL: result.user.photoURL,
      });

      // JWT token is automatically generated by AuthProvider
      toast.success("Login successful!");
      navigate(from, { replace: true });
    } catch (error) {
      console.error("Google sign in error:", error);
      toast.error(
        error.response?.data?.message ||
          error.message ||
          "Google sign in failed"
      );
    } finally {
      setLoading(false);
    }
  };
  return (
    <div className="">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-lg border-b border-gray-200 dark:border-gray-700">
        <div className="container mx-auto px-4 lg:px-8 ">
          <div className="flex items-center h-20">
            <Link to="/" className="flex items-center">
              <img src={logo} alt="TicketBari Logo" className="w-24 -mt-5" />
              <span className="text-2xl lg:text-3xl -mb-10 -ml-10 -mt-8 font-bold text-[#476F97] dark:text-[#5a9bd5] bg-clip-text">
                TicketBari
              </span>
            </Link>
          </div>
        </div>
      </nav>
      <div className=" flex items-center  justify-center  py-12 px-4">
        <div className="max-w-md w-full bg-white dark:bg-gray-800 rounded-2xl shadow-xl p-8 my-10">
          <h2 className="text-3xl font-bold text-center text-gray-800 dark:text-white mb-8">
            Welcome Back
          </h2>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            {/* Email */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Email
              </label>
              <input
                type="email"
                {...register("email", { required: "Email is required" })}
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:text-white"
                placeholder="Enter your email"
              />
              {errors.email && (
                <p className="text-red-500 text-sm mt-1">
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* Password */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Password
              </label>
              <input
                type="password"
                {...register("password", { required: "Password is required" })}
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:text-white"
                placeholder="Enter your password"
              />
              {errors.password && (
                <p className="text-red-500 text-sm mt-1">
                  {errors.password.message}
                </p>
              )}
            </div>

            {/* Forgot Password */}
            <div className="text-right">
              <Link
                to="/forgot-password"
                className="text-sm text-[#09335b] hover:underline"
              >
                Forgot Password?
              </Link>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full text-white py-3 rounded-lg  bg-[#09335b] hover:bg-[linear-gradient(159deg,#377CBD_0%,#09335B_50%,#09335B_100%)] transition font-semibold disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <svg
                    className="animate-spin h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  <span>Logging in...</span>
                </>
              ) : (
                "Login"
              )}
            </button>
          </form>

          <div className="my-6 flex items-center">
            <div className="flex-1 border-t border-gray-300 dark:border-gray-600"></div>
            <span className="px-4 text-sm text-gray-500 dark:text-gray-400">
              OR
            </span>
            <div className="flex-1 border-t border-gray-300 dark:border-gray-600"></div>
          </div>

          <button
            onClick={handleGoogleSignIn}
            type="button"
            className="w-full flex items-center justify-center space-x-2 bg-white dark:bg-gray-700 border-2 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 py-3 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition font-semibold"
          >
            <FaGoogle />
            <span>Continue with Google</span>
          </button>
          {/* Demo Login Section */}
          <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-gray-700 dark:to-gray-600 rounded-xl border border-blue-200 dark:border-gray-600">
            <p className="text-sm font-semibold text-gray-700 dark:text-gray-200 mb-3 text-center">
              🎯 Try Demo Login
            </p>
            <div className="flex items-center justify-center gap-4">
              <button
                type="button"
                onClick={() => handleDemoLogin("vendor")}
                className="px-3 py-2 text-xs font-semibold bg-sky-500 hover:bg-sky-600 text-white rounded-lg transition transform hover:scale-105 shadow"
              >
                Vendor
              </button>
              <button
                type="button"
                onClick={() => handleDemoLogin("admin")}
                className="px-3 py-2 text-xs font-semibold bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition transform hover:scale-105 shadow"
              >
                Admin
              </button>
            </div>
            <p className="text-xs text-gray-600 dark:text-gray-300 mt-2 text-center">
              Click to auto-fill credentials
            </p>
          </div>
          {/* Register Link */}
          <p className="mt-6 text-center text-sm text-gray-600 dark:text-gray-400">
            Don’t have an account?{" "}
            <Link
              to="/register"
              className="text-[#09335b] font-semibold hover:underline"
            >
              Register here
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
